/**
 * Apply SQL shards generated by scripts/sync-to-d1.ts.
 *
 * This is the single entry point for local CI, production deploys, and smoke
 * tests so the .wrangler/sync/*.sql contract does not drift across workflows.
 */

import { existsSync, readdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const V2_ROOT = join(__dirname, '..');
const SYNC_DIR = join(V2_ROOT, '.wrangler', 'sync');
const DB_NAME = process.env.D1_DATABASE_NAME ?? 'management-study-v2';

const mode = process.argv.includes('--remote') ? '--remote' : '--local';

function listShards(): string[] {
  if (!existsSync(SYNC_DIR)) {
    throw new Error(`D1 sync shard directory not found: ${SYNC_DIR}. Run pnpm sync:d1 first.`);
  }

  const files = readdirSync(SYNC_DIR)
    .filter((f) => f.endsWith('.sql'))
    .sort();

  if (files.length === 0) {
    throw new Error(`No D1 sync shards found in ${SYNC_DIR}. Run pnpm sync:d1 first.`);
  }

  return files;
}

function applyShard(file: string) {
  const relPath = `.wrangler/sync/${file}`;
  console.log(`→ applying ${relPath} (${mode})`);
  const res = spawnSync(
    'pnpm',
    ['exec', 'wrangler', 'd1', 'execute', DB_NAME, mode, `--file=${relPath}`],
    {
      cwd: V2_ROOT,
      encoding: 'utf-8',
      stdio: 'inherit',
    },
  );

  if (res.status !== 0) {
    throw new Error(`Failed to apply ${relPath}`);
  }
}

try {
  const shards = listShards();
  console.log(`=== Applying ${shards.length} D1 sync shard(s) to ${DB_NAME} ${mode} ===`);
  for (const shard of shards) applyShard(shard);
  console.log('✓ D1 sync shards applied');
} catch (err) {
  console.error(`✗ ${err instanceof Error ? err.message : err}`);
  process.exit(1);
}
